<?php
// module_load_include('inc', 'services', 'resources/node_resource');

/**
 * Implementation of hook_services_resources().
 */
function pc_commoncode_services_services_resources() {
  $resources['commoncode'] = array();

  return array(
    'commoncode' => array(
        'create' => array(
            'help' => 'Update a commoncode',
            'callback' => 'pc_commoncode_services_update',
            'access callback' => 'pc_commoncode_services_access',
            'args' => array(
                array(
                    'name' => 'code',
                    'optional' => FALSE,
                    'source' => 'data',
                    'type' => 'array',
                    'description' => 'The commoncode name(vocabulary) to update',
                ),
            ),
        ),
    ),
 );

  return $resources;
}

function pc_commoncode_services_access() {

   return TRUE;
}

function pc_commoncode_services_update($code) {
    dsm($code,'code');
    $ret_array['test'] = 'hehehe';
    return $ret_array;
}

?>
