<?php
// module_load_include('inc', 'services', 'resources/node_resource');

/**
 * Implementation of hook_services_resources().
 */
function pc_commoncode_services_services_resources() {
  $resources['commoncode'] = array();

  return array(
    'commoncode' => array(
        'create' => array(
            'help' => 'Update a commoncode',
            'callback' => 'pc_commoncode_services_update',
            'access callback' => 'pc_commoncode_services_access',
            'args' => array(
                 array(
                    'name' => 'code',
                    'optional' => FALSE,
                    'source' => 'data',
                    'description' => 'The data to update',
                    'type' => 'array',
                ),
            ),
        ),
    ),
 );

  return $resources;
}

function pc_commoncode_services_access() {
    return TRUE;
}

function pc_commoncode_services_update($code) {
    global $user;
    $account = user_load(1);
    $user = $account;
    
    $commonCode = _services_arg_value($code, 'code');

	watchdog('CommonCode', 'commonCode : %commonCode', array('%commonCode' => $commonCode));
	error_log('code raw: '.json_encode($code));
    // $commonCode = '{"code":{"svcDomain":"2","sourceLang":"en","description":"Voice(Unitel-Mobile)1","codeGroup":"CallType","meaning":"MOBILE_UNT_TEST","code":"15115","language":"mn","subGrp2":"MOBILE_OFFNET","subGrp1":"VOICE"}}';
    
    $code_list = array();
    $code_list[] = (object)$commonCode;
    
    watchdog('CommonCode', 'code_list : %code_list', array('%code_list' => $code_list));
    
    _commoncode_update_or_create($code_list, $commonCode['codeGroup']);
    
    $ret_array['result'] = 'success';
    return $ret_array;
}

?>
