<?php
/**
 * Implementation of hook_services_resources().
 */
function pc_counter_services_services_resources() {
  $resources['counter'] = array();

  $resources['counter']['retrieve'] = array(
    'help' => 'Retrieves a counter',
    'callback' => 'pc_counter_services_retrieve',
    'access callback' => 'pc_counter_services_access',
    'args' => array(
        array(
            'name' => 'nid',
            'optional' => FALSE,
            'source' => array('path' => 0),
            'type' => 'int',
            'description' => 'The counter id to get',
        ),
    ),
  );
  return $resources;
}

/**
 * Check the access permission to a given views.
 *
 * @param $op
 *  String. The operation that's going to be performed.
 * @param $args
 *  Array. The arguments that will be passed to the callback.
 * @return
 *  Boolean. TRUE if the user is allowed to load the given view.
 */
function pc_counter_services_access() {
   return TRUE;
}

function pc_counter_services_retrieve($counter_id) {
	$jsonData = array();
	$viewResult = views_get_view_result('list_counter', 'panel_pane_13', $counter_id);
	
	if(!empty($viewResult)) {
		$jsonData = _array_export_counter($viewResult[0]->nid);
	} else {
		$jsonData['PCatalog']['result_code'] = '0';
		$jsonData['PCatalog']['result_reason'] = 'Fail';
		$jsonData['PCatalog']['result_description'] = 'Cannot find counter id';
	}
	
	return $jsonData;
}

?>
