<?php
/**
 * Implementation of hook_services_resources().
 */
function pc_counter_services_services_resources() {
  $resources['counter'] = array();

  $resources['counter']['retrieve'] = array(
    'help' => 'Retrieves a counter',
    'callback' => 'pc_counter_services_retrieve',
    'access callback' => 'pc_counter_services_access',
    'args' => array(
        array(
            'name' => 'nid',
            'optional' => FALSE,
            'source' => array('path' => 0),
            'type' => 'int',
            'description' => 'The counter id to get',
        ),
    ),
  );
  return $resources;
}

/**
 * Check the access permission to a given views.
 *
 * @param $op
 *  String. The operation that's going to be performed.
 * @param $args
 *  Array. The arguments that will be passed to the callback.
 * @return
 *  Boolean. TRUE if the user is allowed to load the given view.
 */
function pc_counter_services_access() {
   return TRUE;
}

function pc_counter_services_retrieve($nid) {

	$return_array = _array_export_counter($nid);

    return $return_array[0];
}

?>
