// Created by iWeb 3.0.3 local-build-20110426

function writeMovie1()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id5" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="602" height="392" style="height: 392px; left: 49px; position: absolute; top: 371px; width: 602px; z-index: 1; "><param name="src" value="../../../../Media/InputAttribute.mov" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id5" type="video/quicktime" width="602" height="392" style="height: 392px; left: 49px; position: absolute; top: 371px; width: 602px; z-index: 1; "><param name="src" value="27_Design_Product_files/InputAttribute-1.jpg"/><param name="target" value="myself"/><param name="href" value="../../../../../Media/InputAttribute.mov"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id5" type="video/quicktime" width="602" height="392" data="../../../../Media/InputAttribute.mov" style="height: 392px; left: 49px; position: absolute; top: 371px; width: 602px; z-index: 1; "><param name="src" value="../../../../Media/InputAttribute.mov"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie2()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id9" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="618" height="402" style="height: 402px; left: 41px; position: absolute; top: 939px; width: 618px; z-index: 1; "><param name="src" value="../../../../Media/DesignSubscription.mov" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id9" type="video/quicktime" width="618" height="402" style="height: 402px; left: 41px; position: absolute; top: 939px; width: 618px; z-index: 1; "><param name="src" value="27_Design_Product_files/DesignSubscription-1.jpg"/><param name="target" value="myself"/><param name="href" value="../../../../../Media/DesignSubscription.mov"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id9" type="video/quicktime" width="618" height="402" data="../../../../Media/DesignSubscription.mov" style="height: 402px; left: 41px; position: absolute; top: 939px; width: 618px; z-index: 1; "><param name="src" value="../../../../Media/DesignSubscription.mov"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie3()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id14" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="541" height="354" style="height: 354px; left: 79px; position: absolute; top: 1487px; width: 541px; z-index: 1; "><param name="src" value="../../../../Media/DesignTariff.mov" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id14" type="video/quicktime" width="541" height="354" style="height: 354px; left: 79px; position: absolute; top: 1487px; width: 541px; z-index: 1; "><param name="src" value="27_Design_Product_files/DesignTariff-1.jpg"/><param name="target" value="myself"/><param name="href" value="../../../../../Media/DesignTariff.mov"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id14" type="video/quicktime" width="541" height="354" data="../../../../Media/DesignTariff.mov" style="height: 354px; left: 79px; position: absolute; top: 1487px; width: 541px; z-index: 1; "><param name="src" value="../../../../Media/DesignTariff.mov"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie4()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id19" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="637" height="414" style="height: 414px; left: 31px; position: absolute; top: 2002px; width: 637px; z-index: 1; "><param name="src" value="../../../../Media/DesignBalance.mov" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id19" type="video/quicktime" width="637" height="414" style="height: 414px; left: 31px; position: absolute; top: 2002px; width: 637px; z-index: 1; "><param name="src" value="27_Design_Product_files/DesignBalance-1.jpg"/><param name="target" value="myself"/><param name="href" value="../../../../../Media/DesignBalance.mov"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id19" type="video/quicktime" width="637" height="414" data="../../../../Media/DesignBalance.mov" style="height: 414px; left: 31px; position: absolute; top: 2002px; width: 637px; z-index: 1; "><param name="src" value="../../../../Media/DesignBalance.mov"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie5()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id22" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="632" height="411" style="height: 411px; left: 34px; position: absolute; top: 2592px; width: 632px; z-index: 1; "><param name="src" value="../../../../Media/DesignPromotion.mov" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id22" type="video/quicktime" width="632" height="411" style="height: 411px; left: 34px; position: absolute; top: 2592px; width: 632px; z-index: 1; "><param name="src" value="27_Design_Product_files/DesignPromotion-1.jpg"/><param name="target" value="myself"/><param name="href" value="../../../../../Media/DesignPromotion.mov"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id22" type="video/quicktime" width="632" height="411" data="../../../../Media/DesignPromotion.mov" style="height: 411px; left: 34px; position: absolute; top: 2592px; width: 632px; z-index: 1; "><param name="src" value="../../../../Media/DesignPromotion.mov"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie6()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id26" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="595" height="388" style="height: 388px; left: 52px; position: absolute; top: 3170px; width: 595px; z-index: 1; "><param name="src" value="../../../../Media/DesignVAS.mov" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id26" type="video/quicktime" width="595" height="388" style="height: 388px; left: 52px; position: absolute; top: 3170px; width: 595px; z-index: 1; "><param name="src" value="27_Design_Product_files/DesignVAS-1.jpg"/><param name="target" value="myself"/><param name="href" value="../../../../../Media/DesignVAS.mov"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id26" type="video/quicktime" width="595" height="388" data="../../../../Media/DesignVAS.mov" style="height: 388px; left: 52px; position: absolute; top: 3170px; width: 595px; z-index: 1; "><param name="src" value="../../../../Media/DesignVAS.mov"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie7()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id30" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="635" height="413" style="height: 413px; left: 32px; position: absolute; top: 3743px; width: 635px; z-index: 1; "><param name="src" value="../../../../Media/OverviewAfterCreation.mov" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id30" type="video/quicktime" width="635" height="413" style="height: 413px; left: 32px; position: absolute; top: 3743px; width: 635px; z-index: 1; "><param name="src" value="27_Design_Product_files/OverviewAfterCreation-1.jpg"/><param name="target" value="myself"/><param name="href" value="../../../../../Media/OverviewAfterCreation.mov"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id30" type="video/quicktime" width="635" height="413" data="../../../../Media/OverviewAfterCreation.mov" style="height: 413px; left: 32px; position: absolute; top: 3743px; width: 635px; z-index: 1; "><param name="src" value="../../../../Media/OverviewAfterCreation.mov"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,196),url:'27_Design_Product_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'27_Design_Product_files/stroke_1.png'},{rect:new IWRect(2,-2,416,4),url:'27_Design_Product_files/stroke_2.png'},{rect:new IWRect(418,-2,4,4),url:'27_Design_Product_files/stroke_3.png'},{rect:new IWRect(418,2,4,196),url:'27_Design_Product_files/stroke_4.png'},{rect:new IWRect(418,198,4,4),url:'27_Design_Product_files/stroke_5.png'},{rect:new IWRect(2,198,416,4),url:'27_Design_Product_files/stroke_6.png'},{rect:new IWRect(-2,198,4,4),url:'27_Design_Product_files/stroke_7.png'}],new IWSize(420,200))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('27_Design_Product_files/27_Design_ProductMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');adjustLineHeightIfTooBig('id15');adjustFontSizeIfTooBig('id15');adjustLineHeightIfTooBig('id16');adjustFontSizeIfTooBig('id16');adjustLineHeightIfTooBig('id17');adjustFontSizeIfTooBig('id17');adjustLineHeightIfTooBig('id18');adjustFontSizeIfTooBig('id18');adjustLineHeightIfTooBig('id20');adjustFontSizeIfTooBig('id20');adjustLineHeightIfTooBig('id21');adjustFontSizeIfTooBig('id21');adjustLineHeightIfTooBig('id23');adjustFontSizeIfTooBig('id23');adjustLineHeightIfTooBig('id24');adjustFontSizeIfTooBig('id24');adjustLineHeightIfTooBig('id25');adjustFontSizeIfTooBig('id25');adjustLineHeightIfTooBig('id27');adjustFontSizeIfTooBig('id27');adjustLineHeightIfTooBig('id28');adjustFontSizeIfTooBig('id28');adjustLineHeightIfTooBig('id29');adjustFontSizeIfTooBig('id29');adjustLineHeightIfTooBig('id31');adjustFontSizeIfTooBig('id31');adjustLineHeightIfTooBig('id32');adjustFontSizeIfTooBig('id32');adjustLineHeightIfTooBig('id33');adjustFontSizeIfTooBig('id33');adjustLineHeightIfTooBig('id34');adjustFontSizeIfTooBig('id34');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('../../../../Media/transparent.gif');BlogFixupPreviousNext();applyEffects()}
function onPageUnload()
{Widget.onunload();}
