// Created by iWeb 3.0.3 local-build-20110426

function writeMovie1()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id17" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="631" height="410" style="height: 410px; left: 38px; position: absolute; top: 762px; width: 631px; z-index: 1; "><param name="src" value="../../../../Media/concept005.mp4" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id17" type="video/quicktime" width="631" height="410" style="height: 410px; left: 38px; position: absolute; top: 762px; width: 631px; z-index: 1; "><param name="src" value="30_What_is_the_product_catalog_files/concept-Clip5_1.jpg"/><param name="target" value="myself"/><param name="href" value="../../../../../Media/concept005.mp4"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id17" type="video/quicktime" width="631" height="410" data="../../../../Media/concept005.mp4" style="height: 410px; left: 38px; position: absolute; top: 762px; width: 631px; z-index: 1; "><param name="src" value="../../../../Media/concept005.mp4"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,196),url:'30_What_is_the_product_catalog_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'30_What_is_the_product_catalog_files/stroke_1.png'},{rect:new IWRect(2,-2,416,4),url:'30_What_is_the_product_catalog_files/stroke_2.png'},{rect:new IWRect(418,-2,4,4),url:'30_What_is_the_product_catalog_files/stroke_3.png'},{rect:new IWRect(418,2,4,196),url:'30_What_is_the_product_catalog_files/stroke_4.png'},{rect:new IWRect(418,198,4,4),url:'30_What_is_the_product_catalog_files/stroke_5.png'},{rect:new IWRect(2,198,416,4),url:'30_What_is_the_product_catalog_files/stroke_6.png'},{rect:new IWRect(-2,198,4,4),url:'30_What_is_the_product_catalog_files/stroke_7.png'}],new IWSize(420,200)),stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,234),url:'30_What_is_the_product_catalog_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'30_What_is_the_product_catalog_files/stroke_9.png'},{rect:new IWRect(2,-2,268,4),url:'30_What_is_the_product_catalog_files/stroke_10.png'},{rect:new IWRect(270,-2,4,4),url:'30_What_is_the_product_catalog_files/stroke_11.png'},{rect:new IWRect(270,2,4,234),url:'30_What_is_the_product_catalog_files/stroke_12.png'},{rect:new IWRect(270,236,4,5),url:'30_What_is_the_product_catalog_files/stroke_13.png'},{rect:new IWRect(2,236,268,5),url:'30_What_is_the_product_catalog_files/stroke_14.png'},{rect:new IWRect(-2,236,4,5),url:'30_What_is_the_product_catalog_files/stroke_15.png'}],new IWSize(272,238))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('30_What_is_the_product_catalog_files/30_What_is_the_product_catalogMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');adjustLineHeightIfTooBig('id15');adjustFontSizeIfTooBig('id15');adjustLineHeightIfTooBig('id16');adjustFontSizeIfTooBig('id16');adjustLineHeightIfTooBig('id18');adjustFontSizeIfTooBig('id18');adjustLineHeightIfTooBig('id19');adjustFontSizeIfTooBig('id19');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('../../../../Media/transparent.gif');BlogFixupPreviousNext();applyEffects()}
function onPageUnload()
{Widget.onunload();}
