<?php

/**
 * @file
 * All the element validators for #element_validate.
 */

/**
 * Implements hook_element_info_alter().
 */
function value_is_element_info_alter(&$info) {
  if (isset($info['file'])) {
    if (!isset($info['file']['#validate'])) {
      $info['file']['#validate'] = array();
    }
    array_unshift($info['file']['#validate'], '_value_is_file_element_validate');
    $info['file']['#process'][] = '_value_is_file_element_process';
  }
}

/**
 * Process callback for file input elements.
 */
function _value_is_file_element_process($element, &$form_state, $form) {
  $file = _value_is_get_file($element);
  $error = _value_is_get_file_error($file);

  if (!$error) {
    $element['#value'] = $file;
    form_set_value($element, $file, $form_state);
  }

  return $element;
}

/**
 * Helper to get a file's error code. This requires logic, because a file can be a list of files.
 */
function _value_is_get_file_error($file) {
  if (isset($file[0])) {
    return isset($file[0]['error']) ? $file[0]['error'] : -1;
  }

  return isset($file['error']) ? $file['error'] : -1;
}

/**
 * Helper to get a file from $_FILES.
 */
function _value_is_get_file($element) {
  $input_name = trim(str_replace(array('[', ']'), ' ', str_replace('[]', '', $element['#name'])));
  $input_name_path = preg_split('/\s+/', $input_name);

  // Traverse $_FILES recursively to find the actual file. This is not pretty, but
  // the only (?) way.
  $properties = array('name', 'type', 'tmp_name', 'error', 'size');
  $input_name_part = array_shift($input_name_path);
  foreach ($properties as $prop) {
    $source[$prop] = @$_FILES[$input_name_part][$prop];
    if ($source[$prop] === NULL) {
      return;
    }
  }
  while ($input_name_part = array_shift($input_name_path)) {
    foreach ($properties as $prop) {
      $source[$prop] = @$source[$prop][$input_name_part];
      if ($source[$prop] === NULL) {
        return;
      }
    }
  }

  // Flip array 2d for arrayed/multiple files.
  if ($source && is_array($source['error'])) {
    $source = _value_is_flip_array_2d($source);
  }

  return $source;
}

/**
 * Helper to flip a 2D array.
 */
function _value_is_flip_array_2d($array) {
  $out = array();
  foreach ($array as $a => $children) {
    foreach ($children as $b => $value) {
      $out[$b][$a] = $value;
    }
  }
  return $out;
}

/**
 * Checks for valid (and optionally existing) user name.
 */
function value_is_username($element, &$form_state, $form) {
  $value = $element['#value'];

  if ('' != $value) {
    $must_exist = !empty($element['#exists']);

    if ($must_exist) {
      $field = isset($element['#field']) ? $element['#field'] : 'name';

      $query = db_select('users', 'u');
      $query->addExpression('COUNT(1)', 'num');
      $query->condition($field, $value);

      $exists = (int) $query->execute()->fetchField();

      if (!$exists) {
        $params = array('%title' => $element['#title']);
        $message = t('%title must contain an existing user name.', $params);
        return form_error($element, $message);
      }
    }
    else {
      $error = user_validate_name($value);
      if ($error) {
        return form_error($element, $error);
      }
    }
  }
}

/**
 * Checks for e-mail address(es).
 */
function value_is_email($element, &$form_state, $form) {
  $value = $element['#value'];

  if ('' != $value) {
    // Default is just 1 address.
    $max = isset($element['#max']) ? (int) $element['#max'] : 1;
    // The input will be validated as if it were an array.
    $addresses = explode(',', $value);

    // Too many.
    if ($max < count($addresses)) {
      $params = array('%title' => $element['#title'], '@max' => $max);
      $message = t('%title can contain max @max e-mail addresses.', $params);
      return form_error($element, $message);
    }

    // Validate per address.
    foreach ($addresses as $address) {
      if (!valid_email_address(trim($address))) {
        $params = array('%title' => $element['#title']);
        $message = 1 < $max ?
          t('%title must be a comma separated list of valid e-mail addresses.', $params) :
          t('%title must be a valid e-mail address', $params);
        return form_error($element, $message);
      }
    }
  }
}


/**
 * Helper: integer.
 */
function _value_is_integer($value) {
  return (string) $value === (string) (int) $value;
}

/**
 * Checks for integer (non floating point number).
 */
function value_is_integer($element, &$form_state, $form) {
  $value = $element['#value'];

  if ('' != $value) {
    // Not even close.
    if (!_value_is_integer($value)) {
      return form_error($element, t('Only numbers are allowed in %field.', array(
        '%field' => $element['#title'],
      )));
    }

    // Too low.
    if (isset($element['#min']) && $value < $element['#min']) {
      return form_error($element, t('%name: the value may be no less than %min.', array(
        '%name' => $element['#title'],
        '%min' => $element['#min'],
      )));
    }

    // Too high.
    if (isset($element['#max']) && $value > $element['#max']) {
      return form_error($element, t('%name: the value may be no greater than %max.', array(
        '%name' => $element['#title'],
        '%max' => $element['#max'],
      )));
    }

    // Cast input value to an Int.
    form_set_value($element, (int) $value, $form_state);
  }
}


/**
 * Helper: float.
 */
function _value_is_number(&$value) {
  $value = str_replace(',', '.', $value);
  return is_numeric($value);
}

/**
 * Checks for number (floating point number).
 */
function value_is_number(&$element, &$form_state, $form) {
  $value = $element['#value'];

  if ('' != $value) {
    // Not even close.
    if (!_value_is_number($value)) {
      return form_error($element, t('Only numbers and the decimal separator are allowed in %field.', array(
        '%field' => $element['#title'],
      )));
    }

    // Too low.
    if (isset($element['#min']) && $value < $element['#min']) {
      return form_error($element, t('%name: the value may be no less than %min.', array(
        '%name' => $element['#title'],
        '%min' => $element['#min'],
      )));
    }

    // Too high.
    if (isset($element['#max']) && $value > $element['#max']) {
      return form_error($element, t('%name: the value may be no greater than %max.', array(
        '%name' => $element['#title'],
        '%max' => $element['#max'],
      )));
    }

    // Cast input value to a Float.
    form_set_value($element, (float) $value, $form_state);
  }
}
