// Created by iWeb 3.0.3 local-build-20110426

function writeMovie1()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id6" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="619" height="403" style="height: 403px; left: 41px; position: absolute; top: 410px; width: 619px; z-index: 1; "><param name="src" value="../../../../Media/ActionManagement.mov" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id6" type="video/quicktime" width="619" height="403" style="height: 403px; left: 41px; position: absolute; top: 410px; width: 619px; z-index: 1; "><param name="src" value="23_Action_Management_files/ActionManagement-1.jpg"/><param name="target" value="myself"/><param name="href" value="../../../../../Media/ActionManagement.mov"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id6" type="video/quicktime" width="619" height="403" data="../../../../Media/ActionManagement.mov" style="height: 403px; left: 41px; position: absolute; top: 410px; width: 619px; z-index: 1; "><param name="src" value="../../../../Media/ActionManagement.mov"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,162),url:'23_Action_Management_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'23_Action_Management_files/stroke_9.png'},{rect:new IWRect(2,-2,176,4),url:'23_Action_Management_files/stroke_10.png'},{rect:new IWRect(178,-2,4,4),url:'23_Action_Management_files/stroke_11.png'},{rect:new IWRect(178,2,4,162),url:'23_Action_Management_files/stroke_12.png'},{rect:new IWRect(178,164,4,4),url:'23_Action_Management_files/stroke_13.png'},{rect:new IWRect(2,164,176,4),url:'23_Action_Management_files/stroke_14.png'},{rect:new IWRect(-2,164,4,4),url:'23_Action_Management_files/stroke_15.png'}],new IWSize(180,166)),stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,176),url:'23_Action_Management_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'23_Action_Management_files/stroke_1.png'},{rect:new IWRect(2,-2,374,4),url:'23_Action_Management_files/stroke_2.png'},{rect:new IWRect(376,-2,4,4),url:'23_Action_Management_files/stroke_3.png'},{rect:new IWRect(376,2,4,176),url:'23_Action_Management_files/stroke_4.png'},{rect:new IWRect(376,178,4,4),url:'23_Action_Management_files/stroke_5.png'},{rect:new IWRect(2,178,374,4),url:'23_Action_Management_files/stroke_6.png'},{rect:new IWRect(-2,178,4,4),url:'23_Action_Management_files/stroke_7.png'}],new IWSize(378,180))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('23_Action_Management_files/23_Action_ManagementMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('../../../../Media/transparent.gif');BlogFixupPreviousNext();applyEffects()}
function onPageUnload()
{Widget.onunload();}
