<?php
/**
 * Implementation of hook_services_resources().
 */
function pc_product_services_services_resources() {
  $resources['product'] = array();

  $resources['product']['retrieve'] = array(
    'help' => 'Retrieves a product',
    'callback' => 'pc_product_services_retrieve',
    'access callback' => 'pc_product_services_access',
    'args' => array(
        array(
            'name' => 'nid',
            'optional' => FALSE,
            'source' => array('path' => 0),
            'type' => 'int',
            'description' => 'The product id to get',
        ),
    ),
  );
  return $resources;
}

function pc_product_services_access() {
   return TRUE;
}

function pc_product_services_retrieve($product_id) {
	$jsonData = array();
		$viewResult = views_get_view_result('list_simple_product_offering', 'panel_pane_8', $product_id);
		
		if(!empty($viewResult)) {
			$isExternalAPI = TRUE;
			$jsonData = _product_for_export($viewResult[0]->nid, $isExternalAPI);
		} else {
			$jsonData['PCatalog']['result_code'] = '0';
			$jsonData['PCatalog']['result_reason'] = 'Fail';
			$jsonData['PCatalog']['result_description'] = 'Cannot find product id';
	}
		
	return $jsonData;
}

?>
