// Created by iWeb 3.0.3 local-build-20110426

function writeMovie1()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id14" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="599" height="390" style="height: 390px; left: 56px; position: absolute; top: 458px; width: 599px; z-index: 1; "><param name="src" value="../../../../Media/conditions%28overview%29.mov" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="71" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id14" type="video/quicktime" width="599" height="390" style="height: 390px; left: 56px; position: absolute; top: 458px; width: 599px; z-index: 1; "><param name="src" value="24_Condition_Management_files/conditions%28overview%29-1.jpg"/><param name="target" value="myself"/><param name="href" value="../../../../../Media/conditions%28overview%29.mov"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id14" type="video/quicktime" width="599" height="390" data="../../../../Media/conditions%28overview%29.mov" style="height: 390px; left: 56px; position: absolute; top: 458px; width: 599px; z-index: 1; "><param name="src" value="../../../../Media/conditions%28overview%29.mov"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="71"/><param name="loop" value="false"/></object>');}}
function writeMovie2()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id15" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="608" height="396" style="height: 396px; left: 47px; position: absolute; top: 1191px; width: 608px; z-index: 1; "><param name="src" value="../../../../Media/condition%28who%29.mov" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id15" type="video/quicktime" width="608" height="396" style="height: 396px; left: 47px; position: absolute; top: 1191px; width: 608px; z-index: 1; "><param name="src" value="24_Condition_Management_files/condition%28who%29-1.jpg"/><param name="target" value="myself"/><param name="href" value="../../../../../Media/condition%28who%29.mov"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id15" type="video/quicktime" width="608" height="396" data="../../../../Media/condition%28who%29.mov" style="height: 396px; left: 47px; position: absolute; top: 1191px; width: 608px; z-index: 1; "><param name="src" value="../../../../Media/condition%28who%29.mov"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie3()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id17" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="619" height="403" style="height: 403px; left: 45px; position: absolute; top: 1932px; width: 619px; z-index: 1; "><param name="src" value="../../../../Media/condition%28what%29.mov" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id17" type="video/quicktime" width="619" height="403" style="height: 403px; left: 45px; position: absolute; top: 1932px; width: 619px; z-index: 1; "><param name="src" value="24_Condition_Management_files/condition%28what%29-1.jpg"/><param name="target" value="myself"/><param name="href" value="../../../../../Media/condition%28what%29.mov"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id17" type="video/quicktime" width="619" height="403" data="../../../../Media/condition%28what%29.mov" style="height: 403px; left: 45px; position: absolute; top: 1932px; width: 619px; z-index: 1; "><param name="src" value="../../../../Media/condition%28what%29.mov"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie4()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id18" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="634" height="412" style="height: 412px; left: 39px; position: absolute; top: 2701px; width: 634px; z-index: 1; "><param name="src" value="../../../../Media/condition%28when%29.mov" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id18" type="video/quicktime" width="634" height="412" style="height: 412px; left: 39px; position: absolute; top: 2701px; width: 634px; z-index: 1; "><param name="src" value="24_Condition_Management_files/condition%28when%29-1.jpg"/><param name="target" value="myself"/><param name="href" value="../../../../../Media/condition%28when%29.mov"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id18" type="video/quicktime" width="634" height="412" data="../../../../Media/condition%28when%29.mov" style="height: 412px; left: 39px; position: absolute; top: 2701px; width: 634px; z-index: 1; "><param name="src" value="../../../../Media/condition%28when%29.mov"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie5()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id19" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="643" height="418" style="height: 418px; left: 29px; position: absolute; top: 3464px; width: 643px; z-index: 1; "><param name="src" value="../../../../Media/condition%28where%29.mov" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id19" type="video/quicktime" width="643" height="418" style="height: 418px; left: 29px; position: absolute; top: 3464px; width: 643px; z-index: 1; "><param name="src" value="24_Condition_Management_files/condition%28where%29-1.jpg"/><param name="target" value="myself"/><param name="href" value="../../../../../Media/condition%28where%29.mov"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id19" type="video/quicktime" width="643" height="418" data="../../../../Media/condition%28where%29.mov" style="height: 418px; left: 29px; position: absolute; top: 3464px; width: 643px; z-index: 1; "><param name="src" value="../../../../Media/condition%28where%29.mov"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,176),url:'24_Condition_Management_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'24_Condition_Management_files/stroke_1.png'},{rect:new IWRect(2,-2,374,4),url:'24_Condition_Management_files/stroke_2.png'},{rect:new IWRect(376,-2,4,4),url:'24_Condition_Management_files/stroke_3.png'},{rect:new IWRect(376,2,4,176),url:'24_Condition_Management_files/stroke_4.png'},{rect:new IWRect(376,178,4,4),url:'24_Condition_Management_files/stroke_5.png'},{rect:new IWRect(2,178,374,4),url:'24_Condition_Management_files/stroke_6.png'},{rect:new IWRect(-2,178,4,4),url:'24_Condition_Management_files/stroke_7.png'}],new IWSize(378,180)),stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,246),url:'24_Condition_Management_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'24_Condition_Management_files/stroke_9.png'},{rect:new IWRect(2,-2,296,4),url:'24_Condition_Management_files/stroke_10.png'},{rect:new IWRect(298,-2,4,4),url:'24_Condition_Management_files/stroke_11.png'},{rect:new IWRect(298,2,4,246),url:'24_Condition_Management_files/stroke_12.png'},{rect:new IWRect(298,248,4,4),url:'24_Condition_Management_files/stroke_13.png'},{rect:new IWRect(2,248,296,4),url:'24_Condition_Management_files/stroke_14.png'},{rect:new IWRect(-2,248,4,4),url:'24_Condition_Management_files/stroke_15.png'}],new IWSize(300,250))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('24_Condition_Management_files/24_Condition_ManagementMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');adjustLineHeightIfTooBig('id16');adjustFontSizeIfTooBig('id16');adjustLineHeightIfTooBig('id20');adjustFontSizeIfTooBig('id20');adjustLineHeightIfTooBig('id21');adjustFontSizeIfTooBig('id21');adjustLineHeightIfTooBig('id22');adjustFontSizeIfTooBig('id22');adjustLineHeightIfTooBig('id23');adjustFontSizeIfTooBig('id23');adjustLineHeightIfTooBig('id24');adjustFontSizeIfTooBig('id24');adjustLineHeightIfTooBig('id25');adjustFontSizeIfTooBig('id25');adjustLineHeightIfTooBig('id26');adjustFontSizeIfTooBig('id26');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('../../../../Media/transparent.gif');BlogFixupPreviousNext();applyEffects()}
function onPageUnload()
{Widget.onunload();}
