<?php
module_load_include('inc', 'services', 'resources/node_resource');

/**
 * Implementation of hook_services_resources().
 */
function pc_device_services_services_resources() {
  $resources['device'] = array();

  $resources['device']['create'] = array(
    'help' => 'Create device type',
    'callback' => 'pc_device_services_create',
    'access callback' => 'pc_device_services_access', 
    'args' => array(
        array(
            'name' => 'model',
            'optional' => FALSE,
            'source' => 'data',
            'description' => 'The node data to create',
            'type' => 'array',
        ),
    ),
  );

  $resources['device']['retrieve'] = array(
    'help' => 'Retrieves a device',
    'callback' => 'pc_device_services_retrieve',
    'access callback' => 'pc_device_services_access',
    'args' => array(
        array(
            'name' => 'nid',
            'optional' => FALSE,
            'source' => array('path' => 0),
            'type' => 'int',
            'description' => 'The device id to get',
        ),
    ),
  );

  return $resources;
}

function pc_device_services_access() {
   return TRUE;
}

function pc_device_services_retrieve($nid) {
    $node = node_load($nid);

    $ret_array = array();
    $ret_array['ID'] = $node->nid;
    $ret_array['Model'] = $node->title;
    return $ret_array;
}


function pc_device_services_create($model) {
    ctools_include('node.pages', 'node', '');
    global $user;

    $account = user_load(1);
    $user = $account;

    $device_model = _services_arg_value($model, 'model');
    
    $ret_array = array();
    foreach($device_model as $model){
        $view = views_get_view('list_device_model');
        $view->set_display('panel_pane_2');
        $view->set_arguments(array('0' => $model['devcMdlCd']));
        $view->execute(); 
        
        if(empty($view->result)){//unique checking
            $deviceModel = new StdClass();
            $deviceModel->title = $model['devcMdlNm'];
            $deviceModel->status = 1;
            $deviceModel->uid = 1;
            $deviceModel->type = 'devicemodel';
            $deviceModel->language = 'und';
            $deviceModel->field_model_code['und'][0]['value'] = $model['devcMdlCd'];
            $deviceModel->field_model_class['und'][0]['value'] = $model['clssNm']; 
            $deviceModel->field_model_class_code['und'][0]['value'] = $model['clssCd']; 
        
            node_save($deviceModel);  
            $ret_array[] = array('ID' => $deviceModel->nid );
        }    
    }
    
    return $ret_array;
}


?>
