// Created by iWeb 3.0.3 local-build-20110426

function writeMovie1()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id6" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="642" height="417" style="height: 417px; left: 27px; position: absolute; top: 873px; width: 642px; z-index: 1; "><param name="src" value="../../../../Media/VASManagement-4.mov" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id6" type="video/quicktime" width="642" height="417" style="height: 417px; left: 27px; position: absolute; top: 873px; width: 642px; z-index: 1; "><param name="src" value="21_VAS_management_files/VASManagement-5.jpg"/><param name="target" value="myself"/><param name="href" value="../../../../../Media/VASManagement-4.mov"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id6" type="video/quicktime" width="642" height="417" data="../../../../Media/VASManagement-4.mov" style="height: 417px; left: 27px; position: absolute; top: 873px; width: 642px; z-index: 1; "><param name="src" value="../../../../Media/VASManagement-4.mov"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,456),url:'21_VAS_management_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'21_VAS_management_files/stroke_9.png'},{rect:new IWRect(2,-2,631,4),url:'21_VAS_management_files/stroke_10.png'},{rect:new IWRect(633,-2,4,4),url:'21_VAS_management_files/stroke_11.png'},{rect:new IWRect(633,2,4,456),url:'21_VAS_management_files/stroke_12.png'},{rect:new IWRect(633,458,4,5),url:'21_VAS_management_files/stroke_13.png'},{rect:new IWRect(2,458,631,5),url:'21_VAS_management_files/stroke_14.png'},{rect:new IWRect(-2,458,4,5),url:'21_VAS_management_files/stroke_15.png'}],new IWSize(635,460)),stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,196),url:'21_VAS_management_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'21_VAS_management_files/stroke_1.png'},{rect:new IWRect(2,-2,418,4),url:'21_VAS_management_files/stroke_2.png'},{rect:new IWRect(420,-2,4,4),url:'21_VAS_management_files/stroke_3.png'},{rect:new IWRect(420,2,4,196),url:'21_VAS_management_files/stroke_4.png'},{rect:new IWRect(420,198,4,4),url:'21_VAS_management_files/stroke_5.png'},{rect:new IWRect(2,198,418,4),url:'21_VAS_management_files/stroke_6.png'},{rect:new IWRect(-2,198,4,4),url:'21_VAS_management_files/stroke_7.png'}],new IWSize(422,200))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('21_VAS_management_files/21_VAS_managementMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('../../../../Media/transparent.gif');BlogFixupPreviousNext();applyEffects()}
function onPageUnload()
{Widget.onunload();}
