<?php
/**
 * Implementation of hook_services_resources().
 */
function pc_deposit_scheme_services_services_resources() {
  $resources['deposit_scheme'] = array();

  $resources['deposit_scheme']['retrieve'] = array(
    'help' => 'Retrieves a deposit_scheme',
    'callback' => 'pc_deposit_scheme_services_retrieve',
    'access callback' => 'pc_deposit_scheme_services_access',
    'args' => array(
        array(
            'name' => 'nid',
            'optional' => FALSE,
            'source' => array('path' => 0),
            'type' => 'int',
            'description' => 'The deposit scheme id to get',
        ),
    ),
  );
  return $resources;
}

/**
 * Check the access permission to a given views.
 *
 * @param $op
 *  String. The operation that's going to be performed.
 * @param $args
 *  Array. The arguments that will be passed to the callback.
 * @return
 */
function pc_deposit_scheme_services_access() {
   return TRUE;
}

function pc_deposit_scheme_services_retrieve($deposit_scheme_id) {
	$jsonData = array();
	$viewResult = views_get_view_result('list_vouchercardtype', 'panel_pane_7', $deposit_scheme_id);
	
	if(!empty($viewResult)) {
		$jsonData = _array_voucher_cardtype($viewResult[0]->nid);
	} else {
		$jsonData['PCatalog']['result_code'] = '0';
		$jsonData['PCatalog']['result_reason'] = 'Fail';
		$jsonData['PCatalog']['result_description'] = 'Cannot find Deposit Scheme id';
	}
	
	return $jsonData;
}

?>
