<?php
/**
 * Implementation of hook_services_resources().
 */
function pc_voucher_services_services_resources() {
  $resources['voucher'] = array();

  $resources['voucher']['retrieve'] = array(
    'help' => 'Retrieves a voucher',
    'callback' => 'pc_voucher_services_retrieve',
    'access callback' => 'pc_voucher_services_access',
    'args' => array(
        array(
            'name' => 'nid',
            'optional' => FALSE,
            'source' => array('path' => 0),
            'type' => 'int',
            'description' => 'The voucher id to get',
        ),
    ),
  );
  return $resources;
}

/**
 * Check the access permission to a given views.
 *
 * @param $op
 *  String. The operation that's going to be performed.
 * @param $args
 *  Array. The arguments that will be passed to the callback.
 * @return
 */
function pc_voucher_services_access() {
   return TRUE;
}

function pc_voucher_services_retrieve($voucher_id) {
  module_load_include('inc', 'product_catalog_export', 'export_voucher_cardtype');
  $jsonData = array();
	
	$viewResult = views_get_view_result('list_vouchercardtype', 'panel_pane_7', $voucher_id);
	
	if(!empty($viewResult)) {
		$isExternalAPI = TRUE;
		error_log('view nid:'.$viewResult[0]->nid);
		$jsonData = _array_voucher_cardtype($viewResult[0]->nid, $isExternalAPI);
		
	} else {
		$jsonData['PCatalog']['result_code'] = '0';
		$jsonData['PCatalog']['result_reason'] = 'Fail';
		$jsonData['PCatalog']['result_description'] = 'Cannot find voucher id';
	}
	
	return $jsonData;
}

?>
