<?php
function product_catalog_rules_create_default_counters($vouchercardtype_nid) {

		$viewResult = views_get_view_result('list_counter', 'panel_pane_1', 'MAIN');

		foreach($viewResult as $counter) {
				$counterforvoucher = new stdClass();
				$counterforvoucher->status = 1;
				$counterforvoucher->uid = 1;
				$counterforvoucher->type = 'treenodecounterforvoucher';
				$counterforvoucher->field_ref_counter['und'][0]['nid'] = $counter->nid;
				$counterforvoucher->field_ref_vouchercardtype['und'][0]['nid'] = $vouchercardtype_nid;
				node_save($counterforvoucher);
		}

}
