<?php
module_load_include('inc', 'product_catalog_export');
module_load_include('inc', 'product_catalog_export', 'export_product');
module_load_include('inc', 'product_catalog_export', 'export_numberingplan_domestic');
module_load_include('inc', 'product_catalog_export', 'export_numberingplan_idd');
module_load_include('inc', 'product_catalog_export', 'export_area_code');
module_load_include('inc', 'product_catalog_export', 'export_country_code');
module_load_include('inc', 'product_catalog_export', 'export_timetablefactors');
module_load_include('inc', 'product_catalog_export', 'export_counter');
module_load_include('inc', 'product_catalog_export', 'export_content_rateid');
module_load_include('inc', 'product_catalog_export', 'export_voucher_cardtype');
module_load_include('inc', 'product_catalog_export', 'export_number_special');
module_load_include('inc', 'product_catalog_export', 'export_deposit_scheme');
module_load_include('inc', 'product_catalog_export', 'export_threshold_scheme');
module_load_include('inc', 'product_catalog_export', 'create_export_data');
module_load_include('inc', 'product_catalog_export', 'create_export_meta_data');
module_load_include('inc', 'product_catalog_export', 'gura_export_all');
module_load_include('inc', 'product_catalog_export', 'export_lifecycle_scheme');
module_load_include('inc', 'product_catalog_export', 'export_ocs_config');
module_load_include('inc', 'product_catalog_export', 'export_message');
module_load_include('inc', 'product_catalog_export', 'export_tvchannel');
module_load_include('inc', 'product_catalog_export', 'export_exclusiveness');
module_load_include('inc', 'product_catalog_export', 'export_unittransfer_scheme');


function export_product($export_item_nids=NULL){
    $data = _product_for_export($export_item_nids);
	return json_encode($data);
}

function export_counter($export_item_nids=NULL){
    return _json_counter($export_item_nids);
}

function export_numberingplan_domestic($export_item_nids=NULL){
	return _json_numberingplan_domestic($export_item_nids);
}

function export_numberingplan_idd($export_item_nids=NULL){
	return _json_numberingplan_idd($export_item_nids);
}

function export_area_code(){
	return _json_area_code();
}

function export_country_code(){
	return _json_country_code();
}

function export_timetablefactors(){
	return _json_timetablefactors();
}

function export_content_rateid($export_item_nids=NULL){
	return _json_content_rateid();
}

function export_voucher_cardtype($export_item_nids=NULL){
	return _json_voucher_cardtype($export_item_nids);
}

function export_number_special($export_item_nids=NULL){
	return _json_number_special($export_item_nids);
}

function export_deposit_scheme($export_item_nids=NULL){
    return _json_deposit_scheme($export_item_nids);
}

function export_unittransfer_scheme($export_item_nids=NULL){
    return _json_unittransfer_scheme($export_item_nids);
}

function export_threshold_scheme($export_item_nids=NULL){
    return _json_threshold_scheme($export_item_nids);
}

function export_lifecycle_scheme($export_item_nids=NULL){
	return _json_lifecycle_scheme($export_item_nids);
}

function export_ocs_config(){
	return _json_ocs_config();
}

function export_message($export_item_nids=NULL){
	return _json_message($export_item_nids);
}

function export_tvchannel($export_item_nids=NULL){
    return _json_tvchannel($export_item_nids);
}

function export_exclusiveness($export_item_nids=NULL){
	return _json_exclusiveness($export_item_nids);
}
?>
