<?php

module_load_include('inc', 'youngmin_test');

function youngmin_test_menu() {
    $items = array();
    $items['test/%ctools_js/form'] = array(
        'title' => 'Test',
        'page callback' => 'test_ajax_sample_test',
        'page arguments' => array(1),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    $items['youngmin_test/%ctools_js/edit%'] = array(
        'title' => 'Edit',
        'page callback' => 'youngmin_test_edit_content',
        'page arguments' => array(1,3),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function youngmin_test_get_form(){
	$output='';
	
	//tree
	$formName = 'product_catalog_tree_form';
	$form_state = array();
	$form_state['tree_type'] = 'usage_custom_rule';
	$form_state['node_type'] = 'usage';
	$form_state['type'] = 'usage';
	
	$view = views_get_view('query_usage_by_product');
	$view->set_arguments(array('0'=>'3963', '1' => 'VOICE'));
	$view->execute();
	
	
	if(count($view->result) > 0){										
	  $form_state ['root_nid'] =$view->result[0]->node_field_data_field_ref_usage_nid;
	  $form_state ['service_of_usage'] = '3977';
	  $form = drupal_build_form($formName, $form_state);
	  $output = drupal_render($form);
	}
	
	//content
	$output = $output.'<div id="tree_content_div">haha</div>';
	
	return $output;	
}

/*
function youngmin_test_form_callback($form, &$form_state) {
dsm('youngmin_test_form_callback');
  $form_state['rebuild'] = TRUE;
  //$form_state['rebuild'] = FALSE;
  return $form;
}
*/

function youngmin_test_edit_content($js = NULL, $contentType, $nid){
	//dsm('youngmin_test_edit_content');

	ctools_include('node.pages', 'node', '');
	ctools_include('ajax');

	$node = node_load($nid);
    // dsm($node, 'node');
	
	$form_state = array(
	    'ajax' => TRUE,
	);

	$form_state['build_info']['args'] = array($node);
	
	$form = drupal_build_form($contentType . '_node_form', $form_state);
	
    $form['actions']['submit']['#ajax'] = array(
        //'wrapper' => $contentType . '_node_form',
        //'callback' => 'youngmin_test_form_callback',
        'effect' => 'fade'    
    );
    
    dsm($form,'form');
    /*
    $form['actions']['submit']['#ajax'] = array(
        'wrapper' => 'apple-node-form',
        'callback' => 'node_add_callback',
        'method' => 'replace',
        'effect' => 'fade'
    );
    */
    
    $formRender = drupal_render($form);
	$renderOutput = '<div id="tree_content_div">'.$formRender.'</div>';
	$output[] = $renderOutput;
	$output = ajax_render($output);
    //dsm($form);
	print $output;
    exit;

    /*
	$form = drupal_get_form($contentType . '_node_form', $node);
	// $form = drupal_build_form($contentType . '_node_form', $form_state);
    // $form['#action'] = '/designer/offering/MOBILE/simple/3146/usage/3161/rule';
	
		
	//dsm($output);
	// $form_state['build_info']['args'] = array($node);
	//$output = '<div id="tree_content_div">';
	$output = drupal_render($form);
	//$output .= '</div>';
	// $output = ctools_modal_form_wrapper($contentType . '_node_form', $form_state);

	if (!empty($form_state['executed'])) {
		$output = array();
		$output [] = ajax_command_invoke(NULL, 'changeTreeItemCallback', array($nodeNid, $form_state['node']->title));
		print json_encode($output);
    	exit;  
	}else{
	    // print ajax_render($output);
	    print $output;
		exit;
	}
	*/
}

?>
